// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Pinned to the single canonical file, not the folder. In folder mode Prisma
  // loads every *.prisma under prisma/, which silently redefines User, Session,
  // Account, Verification and TwoFactor from the Better Auth CLI artifact.
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
