import type { HttpParityCase } from '../contracts.js';

export const authenticationParityCases = [
  {
    id: 'auth:google:redirect',
    description: 'Redirect configured web OAuth requests to Google',
    kind: 'http',
    method: 'GET',
    path: '/api/auth/google',
    dynamicPaths: ['$.headers.location'],
  },
  {
    id: 'auth:google:callback',
    description: 'Link or create a Google account, set the JWT cookie and redirect to the app',
    kind: 'http',
    method: 'GET',
    path: '/api/auth/google/callback?code=<google-code>',
    dynamicPaths: ['$.headers.location', '$.cookies.0'],
  },
  {
    id: 'auth:google:mobile',
    description: 'Verify a mobile Google ID token and return the normal login envelope',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/google/mobile',
    body: { idToken: '<google-id-token>', user: { name: 'Ada User', photo: '<photo-url>' } },
    dynamicPaths: ['$.body.token', '$.body.deepLink', '$.body.user.lastLoginAt'],
  },
  {
    id: 'auth:signup',
    description: 'Create a credential account with the legacy verification JSON values',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/signup',
    body: {
      name: 'Ada User',
      username: '<unique-username>',
      email: '<unique-email>',
      password: 'password',
    },
    dynamicPaths: ['$.body.userId'],
  },
  {
    id: 'auth:verify-email',
    description: 'Verify the four-digit code and issue a seven-day JWT',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/verify-email',
    body: { userId: '<unverified-user-id>', verificationCode: '<verification-code>' },
    dynamicPaths: ['$.body.token', '$.body.deepLink'],
  },
  {
    id: 'auth:resend-verification',
    description: 'Rotate the verification code after the one-minute resend interval',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/resend-verification',
    body: { userId: '<unverified-user-id>' },
  },
  {
    id: 'auth:login',
    description: 'Authenticate verified credentials and return the legacy user projection',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/login',
    body: { email: '<verified-email>', password: 'password' },
    dynamicPaths: ['$.body.token', '$.body.deepLink'],
  },
  {
    id: 'auth:login:2fa-required',
    description: 'Return HTTP 200 with requires2FA when credentials are valid but no factor is supplied',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/login',
    body: { email: '<2fa-email>', password: 'password' },
  },
  {
    id: 'auth:profile-completion',
    description: 'Return profile completion requirements for the authenticated user',
    kind: 'http',
    method: 'GET',
    path: '/api/auth/profile-completion',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'auth:me',
    description: 'Return the current authenticated user without sensitive fields',
    kind: 'http',
    method: 'GET',
    path: '/api/auth/me',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'auth:logout',
    description: 'Clear the token cookie with the legacy cookie policy',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/logout',
    dynamicPaths: ['$.cookies.0'],
  },
  {
    id: 'auth:forgot-password',
    description: 'Return the same anti-enumeration response for known and unknown emails',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/forgot-password',
    body: { email: '<account-email>' },
  },
  {
    id: 'auth:reset-password',
    description: 'Verify the one-hour reset JWT and replace the bcrypt password hash',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/reset-password',
    body: { token: '<password-reset-token>', newPassword: 'new-password' },
  },
  {
    id: 'auth:unexpected-error',
    description: 'Preserve public failure messages while omitting raw internal errors',
    kind: 'http',
    method: 'POST',
    path: '/api/auth/login',
    body: { email: '<error-fixture-email>', password: 'password' },
    intentionalExceptions: ['$.body.error'],
  },
] satisfies readonly HttpParityCase[];
