import type { HttpParityCase } from '../contracts.js';

export const interestsParityCases = [
  {
    id: 'interests:list-active',
    description: 'List active interests without authentication',
    kind: 'http',
    method: 'GET',
    path: '/api/interests',
    dynamicPaths: ['$.body.data.0.createdAt', '$.body.data.0.updatedAt'],
  },
  {
    id: 'interests:create-admin',
    description: 'Create an interest with admin and 2FA policy checks',
    kind: 'http',
    method: 'POST',
    path: '/api/interests',
    headers: { authorization: '<admin-token>', 'x-2fa-token': '<totp>' },
    body: { name: 'Technology', displayName: 'Technology' },
    dynamicPaths: [
      '$.body.data.id',
      '$.body.data.createdAt',
      '$.body.data.updatedAt',
    ],
  },
  {
    id: 'interests:update-admin',
    description: 'Update only fields selected by the legacy handler',
    kind: 'http',
    method: 'PUT',
    path: '/api/interests/<interest-id>',
    headers: { authorization: '<admin-token>', 'x-2fa-token': '<totp>' },
    body: { displayName: 'Tech', description: '', isActive: true },
    dynamicPaths: ['$.body.data.updatedAt'],
  },
  {
    id: 'interests:delete-admin',
    description: 'Delete an interest with admin and 2FA policy checks',
    kind: 'http',
    method: 'DELETE',
    path: '/api/interests/<interest-id>',
    headers: { authorization: '<admin-token>', 'x-2fa-token': '<totp>' },
  },
  {
    id: 'user-interests:list',
    description: 'List active interests selected by the authenticated user',
    kind: 'http',
    method: 'GET',
    path: '/api/user/interests',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'user-interests:add',
    description: 'Merge valid interests and mark profile completion',
    kind: 'http',
    method: 'POST',
    path: '/api/user/interests',
    headers: { authorization: '<user-token>' },
    body: { interestIds: ['<interest-id>'] },
  },
  {
    id: 'user-interests:remove',
    description: 'Remove one selected interest',
    kind: 'http',
    method: 'DELETE',
    path: '/api/user/interests/<interest-id>',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'interests:unexpected-error',
    description: 'Preserve the public 500 message while removing raw error disclosure',
    kind: 'http',
    method: 'GET',
    path: '/api/interests',
    intentionalExceptions: ['$.body.error'],
  },
] satisfies readonly HttpParityCase[];
