import type { HttpParityCase } from '../contracts.js';

export const notificationsParityCases = [
  {
    id: 'notifications:get-settings',
    description: 'Return stored settings or the exact legacy defaults',
    kind: 'http',
    method: 'GET',
    path: '/api/notifications/settings',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'notifications:update-settings',
    description: 'Persist and return the raw notification settings JSON',
    kind: 'http',
    method: 'PUT',
    path: '/api/notifications/settings',
    headers: { authorization: '<user-token>' },
    body: {
      global: { pauseAll: false, quietMode: true },
      interactions: { likes: true },
    },
  },
  {
    id: 'notifications:update-push-token',
    description: 'Store a push token for the authenticated user',
    kind: 'http',
    method: 'PUT',
    path: '/api/notifications/push-token',
    headers: { authorization: '<user-token>' },
    body: { pushToken: '<push-token>' },
  },
  {
    id: 'notifications:list',
    description: 'List the user notification inbox with filtering and pagination',
    kind: 'http',
    method: 'GET',
    path: '/api/notifications?page=1&limit=20&type=LIKE',
    headers: { authorization: '<user-token>' },
    dynamicPaths: [
      '$.body.notifications.0.id',
      '$.body.notifications.0.createdAt',
      '$.body.notifications.0.updatedAt',
    ],
  },
  {
    id: 'notifications:unread-count',
    description: 'Count unread notifications owned by the authenticated user',
    kind: 'http',
    method: 'GET',
    path: '/api/notifications/unread-count',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'notifications:mark-read',
    description: 'Mark one owned notification as read',
    kind: 'http',
    method: 'PUT',
    path: '/api/notifications/<notification-id>/read',
    headers: { authorization: '<user-token>' },
    dynamicPaths: ['$.body.updatedAt'],
  },
  {
    id: 'notifications:mark-all-read',
    description: 'Mark all unread notifications for the current user as read',
    kind: 'http',
    method: 'PUT',
    path: '/api/notifications/read-all',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'notifications:delete',
    description: 'Delete one notification owned by the current user',
    kind: 'http',
    method: 'DELETE',
    path: '/api/notifications/<notification-id>',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'notifications:safe-unexpected-error',
    description: 'Preserve the exact stable internal-error response',
    kind: 'http',
    method: 'GET',
    path: '/api/notifications/unread-count',
    headers: { authorization: '<user-token>' },
  },
] satisfies readonly HttpParityCase[];
