import type { HttpParityCase } from '../contracts.js';

export const supportParityCases = [
  {
    id: 'support:create-ticket',
    description: 'Create an authenticated support ticket with default priority',
    kind: 'http',
    method: 'POST',
    path: '/api/support/tickets',
    headers: { authorization: '<user-token>' },
    body: {
      subject: 'Account help',
      description: 'I need help',
      category: 'account',
    },
    dynamicPaths: [
      '$.body.ticket.id',
      '$.body.ticket.createdAt',
      '$.body.ticket.updatedAt',
    ],
  },
  {
    id: 'support:list-user-tickets',
    description: 'List only tickets owned by the authenticated user',
    kind: 'http',
    method: 'GET',
    path: '/api/support/tickets',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'support:get-ticket',
    description: 'Load ticket details, ordered messages and ownership policy',
    kind: 'http',
    method: 'GET',
    path: '/api/support/tickets/<ticket-id>',
    headers: { authorization: '<user-token>' },
  },
  {
    id: 'support:add-message',
    description: 'Add a reply and apply the sender-dependent ticket status transition',
    kind: 'http',
    method: 'POST',
    path: '/api/support/tickets/<ticket-id>/messages',
    headers: { authorization: '<user-token>' },
    body: { message: 'Additional details', attachments: [] },
    dynamicPaths: ['$.body.message.id', '$.body.message.createdAt'],
  },
  {
    id: 'support:update-status',
    description: 'Allow owners to close or resolve while administrators may set any legacy status',
    kind: 'http',
    method: 'PATCH',
    path: '/api/support/tickets/<ticket-id>/status',
    headers: { authorization: '<user-token>' },
    body: { status: 'resolved' },
    dynamicPaths: ['$.body.ticket.updatedAt'],
  },
  {
    id: 'support:list-admin-tickets',
    description: 'List filtered administrator tickets with legacy pagination',
    kind: 'http',
    method: 'GET',
    path: '/api/support/admin/tickets?page=1&limit=20',
    headers: { authorization: '<admin-token>' },
  },
  {
    id: 'support:update-priority',
    description: 'Update ticket priority as an administrator',
    kind: 'http',
    method: 'PATCH',
    path: '/api/support/admin/tickets/<ticket-id>/priority',
    headers: { authorization: '<admin-token>' },
    body: { priority: 'high' },
    dynamicPaths: ['$.body.ticket.updatedAt'],
  },
  {
    id: 'support:unexpected-error',
    description: 'Retain the 500 status while replacing raw persistence errors with Server error',
    kind: 'http',
    method: 'GET',
    path: '/api/support/tickets',
    headers: { authorization: '<user-token>' },
    intentionalExceptions: ['$.body.error'],
  },
] satisfies readonly HttpParityCase[];
